apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: 31723e97-eedd-4835-844c-a172e37a3fd0
spec:
  dn:
    nodeSelector:
      tke.matrixorigin.io/mo-checkin-regression: "true"
    overlay:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/mo-checkin-regression
          operator: Exists
      env:
        - name: GOMEMLIMIT
          value: "8000MiB"
    cacheVolume:
      size: 100Gi
      storageClassName: cbs-hssd
    sharedStorageCache:
      memoryCacheSize: 512Mi
      diskCacheSize: 100Gi
    config: |
      [dn.Txn.Storage]
      backend = "TAE"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = 100
      scan-interval = "5s"
      incremental-interval = "60s"
      global-interval = "100000s"
      [dn.LogtailServer]
      rpc-max-message-size = "16KiB"
      rpc-payload-copy-buffer-size = "16KiB"
      rpc-enable-checksum = true
      memoryCacheSize: 1Gi
      diskCacheSize: 100Gi
    config: |
      [cn.Engine]
      type = "distributed-tae"
      [log]
      level = "info"
      format = "json"
      max-size = 512
      [cn.rpc]
      send-queue-size = 2
      busy-queue-size = 1
      [cn.ctl.address]
      listen-address = "0.0.0.0:19958"
    replicas: 2
    nodeSelector:
      tke.matrixorigin.io/mo-checkin-regression: "true"
    overlay:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/mo-checkin-regression
          operator: Exists
      env:
        - name: GOMEMLIMIT
          value: "8000MiB"
    resources:
      requests:
        cpu: 7
        memory: 12Gi
      limits:
        cpu: 8
        memory: 16Gi
  version: nightly-4bcff5bc