apiVersion: batch/v1
kind: Job
metadata:
  labels:
    mo.chaos.data: "true"
  name: create-databases-with-log-pod-del
spec:
  template:
    metadata:
      labels:
        mo.chaos.data: "true"
    spec:
      containers:
      - name: create-databases-with-log-pod-del
        image: matrixorigin/mo-chaos-data:1.2.3-beta2
        env:
          - name: DURATION
            value: "1800"
          - name: LOCAL_DEBUG
            value: "false"
          - name: CHAOS_JOBS
            value: "log-pod-delete"
          - name: ACTIONS_RUNNER_POD_NAME
            value: $ACTIONS_RUNNER_POD_NAME
          - name: GITHUB_WORKSPACE
            value: $GITHUB_WORKSPACE
        command:
          - "python"
          - "main.py"
      restartPolicy: Never
      serviceAccountName: chaos-job-runner
  backoffLimit: 0
#  ttlSecondsAfterFinished: 5
