apiVersion: batch/v1
kind: Job
metadata:
  labels:
    mo.chaos.data: "true"
  name: create-databases-with-cn-pod-del-all
spec:
  template:
    metadata:
      labels:
        mo.chaos.data: "true"
    spec:
      containers:
      - name: create-databases-with-cn-pod-del-all
        image: matrixorigin/mo-chaos-data:1.2.0-beta3
        env:
          - name: DURATION
            value: "1800"
          - name: LOCAL_DEBUG
            value: "false"
          - name: CHAOS_JOBS
            value: "cn-pod-delete-job-all"
          - name: ACTIONS_RUNNER_POD_NAME
            value: $ACTIONS_RUNNER_POD_NAME
          - name: GITHUB_WORKSPACE
            value: $GITHUB_WORKSPACE
        command:
          - "python"
          - "main.py"
      restartPolicy: Never
      serviceAccountName: chaos-job-runner
  backoffLimit: 0
#  ttlSecondsAfterFinished: 5
