apiVersion: batch/v1
kind: Job
metadata:
  labels:
    mo.chaos.data: "true"
  name: create-databases
spec:
  template:
    spec:
      containers:
      - name: create-databases
        image: matrixorigin/mo-chaos-data:1.0.0-beta4
        env:
          - name: DURATION
            value: "120"
          - name: LOCAL_DEBUG
            value: "false"
          - name: WATCH_JOBS
            value: "$watch_jobs"
        command:
          - "python"
          - "main.py"
      restartPolicy: Never
      serviceAccountName: chaos-job-runner
  backoffLimit: 0
#  ttlSecondsAfterFinished: 5
