name: Deploy Mo Cluster and Run Chaos Experiment on TKE
on:
  workflow_dispatch:
jobs:
  install-mo-cluster:
    runs-on: amd64-tke-dind
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: |
           chmod +x .github/workflows/tke/install-mo.sh
           .github/workflows/tke/install-mo.sh test-chaos
        shell: bash
      - name: Cleanup
        if: always()
        run: |
          chmod +x .github/workflows/tke/clean-mo.sh
          .github/workflows/tke/clean-mo.sh test-chaos
        shell: bash
