kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: mo-io-stress
  namespace: litmus
spec:
  templates:
    - name: custom-chaos
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
            arguments: {}
        - - name: pod-io-stress-4ma
            template: pod-io-stress-4ma
            arguments: {}
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: pod-io-stress-4ma
            path: /tmp/pod-io-stress-4ma.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    IO stress on a app pods belonging to an app deployment
                kind: ChaosExperiment
                metadata:
                  name: pod-io-stress
                  labels:
                    name: pod-io-stress
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-io-stress
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "120"
                      - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                        value: "10"
                      - name: FILESYSTEM_UTILIZATION_BYTES
                        value: ""
                      - name: NUMBER_OF_WORKERS
                        value: "4"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: VOLUME_MOUNT_PATH
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: NODE_LABEL
                        value: ""
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:2.14.0
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: SOCKET_PATH
                        value: /var/run/docker.sock
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-io-stress
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/runtime-api-usage: "true"
                      app.kubernetes.io/version: 2.14.0
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.14.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/pod-io-stress-4ma.yaml -n
            {{workflow.parameters.adminModeNamespace}} &&  sleep 30
        resources: {}
    - name: pod-io-stress-4ma
      inputs:
        artifacts:
          - name: pod-io-stress-4ma
            path: /tmp/chaosengine-pod-io-stress-4ma.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-io-stress-4ma
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                spec:
                  components:
                    runner:
                      tolerations:
                        - key: node-role.kubernetes.io/mo-checkin-regression
                          operator: Exists
                          effect: NoSchedule
                  engineState: active
                  appinfo:
                    appns: $namespace
                    applabel: $label
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-io-stress
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "$duration"
                            - name: FILESYSTEM_UTILIZATION_BYTES
                              value: "$filesystem_utilization_bytes"
                            - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                              value: "0"
                            - name: PODS_AFFECTED_PERC
                              value: '100'
                            - name: TARGET_PODS
                              value: $target_pods
                            - name: NUMBER_OF_WORKERS
                              value: "$workers"
                            - name: LIB_IMAGE
                              value: wxt432/chaos-go-runner:2.14.1-mo-beta3
                            - name: PODS_AFFECTED_PERC
                              value: ""
                            - name: VOLUME_MOUNT_PATH
                              value: /var/lib/matrixone
                            - name: CONTAINER_RUNTIME
                              value: containerd
                            - name: SOCKET_PATH
                              value: /var/run/containerd/containerd.sock
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:2.14.0
        args:
          - -file=/tmp/chaosengine-pod-io-stress-4ma.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: custom-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true