apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-chaos-example
  namespace: chaos-mesh
spec:
  action: random
  mode: all
  patterns:
    - google.com
    - chaos-mesh.*
    - github.?om
  selector:
    namespaces:
      - busybox