apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: one
  duration: '30s'
  selector:
    #labelSelectors:
    #  'app.kubernetes.io/component': 'tikv'
    pods:
      mo-chaos:
        - mo-dis-tp-cn-fnldv