name: Deploy Mo Cluster and Run Chaos Experiment on TKE
on:
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: amd64-tke-dind
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          COS_AK: ${{ secrets.COS_AK }}
          COS_SK: ${{ secrets.COS_SK }}
        run: |
          chmod +x .github/workflows/tke/install-mo.sh
          .github/workflows/tke/install-mo.sh
        shell: bash
      - name: Upload mo cluster artifact
        uses: actions/upload-artifact@v3
        with:
          name: mo-cluster
          path: |
            name
  Wait-Until-Ready:
    runs-on: amd64-tke-dind
    needs:
      - Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - name: Wait
        run: |
          chmod +x .github/workflows/tke/wait.sh
          .github/workflows/tke/wait.sh
        shell: bash
  bvt_test:
    name: MO CHECKIN BVT TEST
    runs-on: amd64-tke-mo
    needs:
      - Wait-Until-Ready
    steps:
      - name: Clone MO-Tester
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-tester
          path: ./mo-tester
          ref: main
      - name: Clone matrixone Repo
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/matrixone
          ref: main
          path: ./matrixone
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - name: Set JAVA PATH
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
      - name: Generate MO-Tester Config and Start BVT Test
        timeout-minutes: 20
        run: |
          name=$(cat name)
          NAMESPACE=chaos-$name
          export LC_ALL="C.UTF-8"
          locale
          sed -i "s/127.0.0.1:6001/$name-tp-cn.$NAMESPACE:6001/" ./mo-tester/mo.yml
          sed -i 's/socketTimeout:.*/socketTimeout: 300000/g' ./mo-tester/mo.yml
          sed -i 's/waittime:.*/waittime: 2000/g' ./mo-tester/run.yml
          cat ./mo-tester/mo.yml
          echo "=========================="
          cat ./mo-tester/run.yml
          echo "=========================="
          
          cd $GITHUB_WORKSPACE/mo-tester
          ./run.sh -n -g -o -p $GITHUB_WORKSPACE/matrixone/test/distributed/cases -s $GITHUB_WORKSPACE/matrixone/test/distributed/resources -e optimistic  2>&1
  Run-Chaos:
    runs-on: amd64-tke-dind
    needs:
      - Wait-Until-Ready
    steps:
      - uses: actions/checkout@v4
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - run: |
          chmod +x .github/workflows/tke/run-chaos.sh
          .github/workflows/tke/run-chaos.sh
        shell: bash
        name: Run
  Cleanup:
    runs-on: amd64-tke-dind
    if: always()
    needs:
      - Run-Chaos
      - bvt_test
    steps:
      - uses: actions/checkout@v4
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - name: Cleanup
        run: |
          chmod +x .github/workflows/tke/clean-mo.sh
          .github/workflows/tke/clean-mo.sh
        shell: bash