name: Deploy Mo Cluster and Run Chaos Experiment on TKE
on:
  workflow_dispatch:
#defaults:
#  run:
#    working-directory: /root
jobs:
  install-mo-cluster:
    runs-on: amd64-tke-dind
    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: |
           chmod +x .github/workflows/install-mo-tke.sh
           .github/workflows/install-mo-tke.sh
        shell: bash