name: Deploy Mo Cluster and Run Chaos Experiment on TKE
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: amd64-tke-dind
    steps:
      - uses: actions/checkout@v2
      - run: |
           chmod +x .github/workflows/tke/install-mo.sh
           .github/workflows/tke/install-mo.sh test-chaos
        shell: bash
#  run-chaos:
#    runs-on: amd64-tke-dind
#    needs:
#      - deploy
#    container:
#      image: matrixorigin/mo-chaos-driller:1.0.0-beta9
#    steps:
#      - run: ls
  cleanup:
    runs-on: amd64-tke-dind
    if: always()
    needs:
      - deploy
#      - run-chaos
    steps:
#      - run: |
#          chmod +x .github/workflows/tke/clean-mo.sh
#          .github/workflows/tke/clean-mo.sh test-chaos
#        shell: bash
      - run: ls