name: Deploy Mo Cluster and Run Chaos Experiment on TKE
on:
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: amd64-tke-dind
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          COS_AK: ${{ secrets.COS_AK }}
          COS_SK: ${{ secrets.COS_SK }}
        run: |
          chmod +x .github/workflows/tke/install-mo.sh
          .github/workflows/tke/install-mo.sh
        shell: bash
      - name: Upload mo cluster artifact
        uses: actions/upload-artifact@v3
        with:
          name: mo-cluster
          path: |
            name
  Wait-Until-Ready:
    runs-on: amd64-tke-dind
    needs:
      - Deploy
    steps:
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - name: Wait
        run: |
          chmod +x .github/workflows/tke/wait.sh
          .github/workflows/tke/wait.sh
        shell: bash
  bvt_test:
    name: MO CHECKIN BVT TEST
    runs-on: amd64-tke-mo
    needs:
      - Wait-Until-Ready
    steps:
      - name: Clone MO-Tester
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/mo-tester
          path: ./mo-tester
          ref: main
      - name: Clone matrixone Repo
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/matrixone
          ref: main
          path: ./matrixone
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - name: Set JAVA PATH
        run: |
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
      - name: Generate MO-Tester Config and Start BVT Test
        timeout-minutes: 20
        run: |
          chmod +x .github/workflows/tke/run-test.sh
          .github/workflows/tke/run-test.sh
        shell: bash
  Run-Chaos:
    runs-on: amd64-tke-dind
    needs:
      - Wait-Until-Ready
    steps:
      - uses: actions/checkout@v2
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - run: |
          chmod +x .github/workflows/tke/run-chaos.sh
          .github/workflows/tke/run-chaos.sh
        shell: bash
        name: Run
  Cleanup:
    runs-on: amd64-tke-dind
    if: always()
    needs:
      - Run-Chaos
      - bvt_test
    steps:
      - uses: actions/checkout@v2
      - name: Download mo cluster artifact
        uses: actions/download-artifact@v3
        with:
          name: mo-cluster
          path: .
      - name: Cleanup
        run: |
          chmod +x .github/workflows/tke/clean-mo.sh
          .github/workflows/tke/clean-mo.sh
        shell: bash