name: Deploy Mo Cluster and Run Chaos Experiment on TKE
on:
  workflow_dispatch:
#defaults:
#  run:
#    working-directory: /root
jobs:
  install-mo-cluster:
    runs-on: amd64-tke-dind
    steps:
      - name: Run install script
        run: bash install-mo-tke.sh