name: Docker Image CI

on:
  push:
    branches:
#      - dev
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: matrixorigin/mo-chaos-driller:${{ github.ref_name }},matrixorigin/mo-chaos-driller:latest
          platforms: linux/amd64
          file: ./litmus/scenarios/Dockerfile
          context: ./litmus/scenarios